# fly.toml — SQLite + Volume (safe)
app = "zoom-booking"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "zoom_data"
  destination = "/app/data"
