services:
  - type: web
    name: zoom-hall-booking
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_EMAIL
        value: admin@site.local
      - key: DEFAULT_ADMIN_PASS
        value: Admin#2025
